version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '3000:80'
    networks:
      - yii2_network
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80" 
    environment:
      - PGADMIN_DEFAULT_EMAIL=yii2@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - yii2_network
      
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=yii2_db
    networks:
      yii2_network:
            ipv4_address: 172.10.0.2


networks:
  yii2_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.0.1